### ISSUE TITLE
A little Change in Your Profile Readme

### ISSUE THREAD

**Issue by JayantGoel001** [ananya26-vishnoi/ananya26-vishnoi#1]
Hi @ananya26-vishnoi,
I just saw your README profile where you using Gitwar Profile Score but facing some issues.
![image](https://user-images.githubusercontent.com/54479676/120245112-cf59a980-c289-11eb-8465-5c79b348658d.png)

I would like to help you with this issue
The issue here is you are using this URL for fetching data

```https://img.shields.io/badge/dynamic/json?label=Gitwar%20Profile%20Score&style=for-the-badge&color=ee6f57&logo=github&logoColor=white&query=score&url=http%3A%2F%2Fgitwar-ananya26-vishnoi.herokuapp.com%2Fapi%2Fananya26-vishnoi```

but for this to work you need to have a Heroku application deployed with the name
```gitwar-ananya26-vishnoi```.

You can simply deploy the same by taking help from the original repo (https://github.com/iampavangandhi/Gitwar#deployment)
and naming the Heroku application as **gitwar-ananya26-vishnoi**.

Hope this helps you.

**Comment by ananya26-vishnoi** [comment]
Thank you, I'll try this and correct my Gitwar profile.
